### PR TITLE
add charts/its a school night

### PR DESCRIPTION
**Pull request by awdev1**
Added charts for the remaining airports as much as I could under pressure from formic, except OWO and SHV, as these airports/seaport barely exist anymore.

### CODE REVIEW

**Review by FormicAcidGD — APPROVED** [review]
LGTM

**Comment by awdev1** [comment]
> LGTM
> 
> 

Deployment when lol

Thanks,
awdev

**Comment by FormicAcidGD** [comment]
> Deployment when lol

never lmfao

**Comment by awdev1** [comment]
the despair is real

**Pull request merged**
