### PR TITLE
Change README and Add Download Function to chart button

### PR DESCRIPTION
**Pull request by awdev1**
# git was sketchy once again but it seems fine (but you might wanna check it before we deploy it at all kinda dont want to take down production)

- corrected 24 Charts to 24Charts
- Added download button to the chart listing
- add discord embed when link sent
image

# as always the diff on the files are goofy once more (thanks vs)
most of the stuff it says i removed isn't actually gone
image
image
works on my system and somewhat "extensively" tested
planning to add download format selector pdf png whatever

### CODE REVIEW

**Comment by FormicAcidGD** [comment]
ill consult the council about this @awdev1 
acid

**Comment by awdev1** [comment]
can we merge this?

**Review by FormicAcidGD — APPROVED** [review]
im just gonna trust you buddy

**Comment by awdev1** [comment]
and took down cloudflare and iccan 💀

**Pull request merged**
